### ISSUE TITLE
User Story: Create a new blank Django project and apps

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/pp4v2#2]
As a **Developer** I can **create a new project and initial app** so that **I have an empty working app**

## Acceptance Criteria
**Given** that this will be a Django project
**When** apps can be created
**Then** we can create the first app to test the server

## Tasks
- [ ] Task 1 – Create the Django project – called XXXXXX
- [ ] Task 2 – Create the first app – called YYYY and add it to the installed apps in the settings.py
- [ ] Task 3 – Migrate Changes
- [ ] Task 4 – Run Server to Test

## EPIC: #3
